export const UPDATE_GRID_SIZE = 'UPDATE_GRID_SIZE';
export const SELECT_NEW_ALGO = 'SELECT_NEW_ALGO';
export const GENERATING_NEW_MAZE = 'GENERATING_NEW_MAZE';
export const MAZE_GENERATED = 'MAZE_GENERATED';
export const SEARCHING_SOLUTION = 'SEARCHING_SOLUTION';
export const SOLUTION_FOUND = 'SOLUTION_FOUND';
