export const SET_GRID_SIZE = 'SET_GRID_SIZE';
export const SELECT_ALGO = 'SELECT_ALGO';
export const MAZE_GENERATION_INIT = 'MAZE_GENERATION_INIT';
export const MAZE_GENERATION_SUCCESS = 'MAZE_GENERATION_SUCCESS';
export const SOLUTION_SEARCH_INIT = 'SOLUTION_SEARCH_INIT';
export const SOLUTION_SEARCH_SUCCESS = 'SOLUTION_SEARCH_SUCCESS';
