export { default as applyDropShadow } from './applyDropShadow';
export { checkIsMobile, checkIsTablet, checkIsBigTablet } from './checkDevice';
export { default as createDOMElement } from './createDOMElement';
export { default as deepCloneObj } from './deepCloneObj';
export { default as delay } from './delay';
export { default as getOppositeDir } from './getOppositeDir';
export { default as getRandomIndex } from './getRandomIndex';
export { default as getStartOrEndIndexOfArray } from './getStartOrEndIndexOfArray';
export { loadStartNodeSprites, loadTargetNodeSprites } from './loadSprites';
export { default as setInitialGridSize } from './setInitialGridSize';
export { default as setupCanvases } from './setupCanvases';
export { shuffleArr, shuffleArrIndices } from './shuffleArray';
export { default as createStore } from './Store';
export { default as swapItemsInArray } from './swapItemsInArray';
